feature: miracle can now integrate with systemd in a meaningful way
miracle-wm-org/miracle-wm pull request #228
Opened 2024-09-04 23:22 UTC by mattkae

2024-09-04 23:38 UTC, Conan-Kudo requested changes
Looks mostly good, just a couple of things...

2024-09-04 23:38 UTC, Conan-Kudo commented on session/README.md
> +echo $XDG_SESSION_DESKTOP  # This should be "miracle-wm"
We should use `mir:miracle` here, assuming we want things that look for mir to work here.

2024-09-04 23:38 UTC, Conan-Kudo commented on session/usr/bin/libexec/miracle-wm/session.sh
> +export XDG_SESSION_DESKTOP="${XDG_SESSION_DESKTOP:-miracle-wm}"
Same here about `mir:miracle`

2024-09-05 17:32 UTC, Conan-Kudo commented on session/README.md
> +echo $XDG_SESSION_DESKTOP  # This should be "miracle-wm"
So according to @alebastr, `XDG_CURRENT_DESKTOP` can be `mir:miracle-wm` but `XDG_SESSION_DESKTOP` can't. So let's not bother then.

2024-09-05 17:32 UTC, Conan-Kudo commented on session/usr/bin/libexec/miracle-wm/session.sh
> +export XDG_SESSION_DESKTOP="${XDG_SESSION_DESKTOP:-miracle-wm}"
Let's not bother.

2024-09-05 17:34 UTC, Conan-Kudo commented
From @alebastr in Matrix:

> since you don't have the same constraints as me, you can move parts of the `session.sh` to miracle-wm-session. The only things that really need to be delayed until the compositor is ready are:
>
> * exporting variables set by the compositor: `DISPLAY`, `WAYLAND_DISPLAY`, `SWAYSOCK`
> * starting the session target
>
> Even `session-shutdown.target` can be invoked after the compositor exits.

2024-09-05 19:29 UTC, Conan-Kudo commented on session/README.md
> +echo $XDG_SESSION_DESKTOP  # This should be "mir:miracle-wm"
This is `miracle-wm`, `$XDG_CURRENT_DESKTOP` is set to `mir:miracle-wm`.

2024-09-05 20:46 UTC, Conan-Kudo commented
Nope, put that Xwayland fix in a separate PR. 😛

2024-09-05 20:49 UTC, mattkae commented
You caught me :( https://github.com/miracle-window-manager/miracle-wm/pull/237

2024-09-05 20:52 UTC, Conan-Kudo requested changes

2024-09-05 20:52 UTC, Conan-Kudo commented on session/usr/local/share/wayland-sessions/miracle-wm.desktop.in
> +Exec=sh -l -c @CMAKE_INSTALL_FULL_BINDIR@/miracle-wm-session
We shouldn't need to do `sh -l -c` anymore?

2024-09-05 21:02 UTC, mattkae commented on session/usr/local/share/wayland-sessions/miracle-wm.desktop.in
> +Exec=sh -l -c @CMAKE_INSTALL_FULL_BINDIR@/miracle-wm-session
True

2024-09-05 21:08 UTC, Conan-Kudo requested changes

2024-09-05 21:08 UTC, Conan-Kudo commented on session/usr/bin/libexec/miracle-wm/session.sh
> +#    therefore the script will ensure that it is always set to `sway`.
`sway` -> `miracle-wm`

2024-09-05 21:08 UTC, Conan-Kudo commented on session/usr/bin/libexec/miracle-wm/session.sh
> +#    - I3SOCK/SWAYSOCK - allow services to talk with sway using i3 IPC protocol
`sway` -> `miracle-wm`

2024-09-05 21:19 UTC, Conan-Kudo requested changes

2024-09-05 21:19 UTC, Conan-Kudo commented on session/README.md
> +following apps will rely on the environment variables set here.
This is probably not the architecture we want here, because then it's easy to accidentally break it. This needs to be triggered from the main wrapper script.

2024-09-07 12:57 UTC, mattkae commented on session/README.md
> +following apps will rely on the environment variables set here.
Yup, I did something different since it was easier for the time being, but now the user can build with `-DSYSTEMD_INTEGRATION` and it will handle all of this for them regardless of their config

2024-09-07 12:59 UTC, Conan-Kudo requested changes

2024-09-07 12:59 UTC, Conan-Kudo commented on session/README.md
> +following apps will rely on the environment variables set here.
This shouldn't be needed anymore now that we have the desktop file pointing to the wrapper script that launches everything, right?

2024-09-07 13:02 UTC, mattkae commented on session/README.md
> +following apps will rely on the environment variables set here.
Done, the instruction should say to modify the runner script

2024-09-07 13:04 UTC, Conan-Kudo approved these changes
I think we're finally good to go.

2024-09-07 13:07 UTC, merged